import { Heading, Text, Button } from "@chakra-ui/react";
import Head from "next/head";
import Container from "../components/Container";

export default function Home() {
  return (
    <>
      <Head>
        <title>My Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Container>
        <Heading>Hello, I'm Melisa Deniz</Heading>
        <Text fontSize="2xl" my={4}>
          A frontend developer and lifelong learner.
        </Text>
        <Button colorScheme="green" size="lg">
          Hire Me!
        </Button>
      </Container>
    </>
  );
}